using System.Text.RegularExpressions;
using CommandLine;

namespace WinGitFS;

internal enum GitProvider { AzureDevOps, GitHub, Generic }

internal sealed class GitFsOptions
{
    [Value(0, MetaName = "url", Required = true, HelpText = "Git repository URL. Supports Azure DevOps, GitHub, or any Git clone URL:\n  ADO: https://dev.azure.com/org/Project/_git/Repo?path=/Apps/MyApp&version=GBmain\n  GitHub: https://github.com/owner/repo/tree/branch/path\n  Generic: https://gitlab.com/owner/repo.git (use --branch and --remote-path)")]
    public string Url { get; set; } = "";

    [Value(1, MetaName = "local-path", Required = false, HelpText = "Local folder path for virtualization root (optional; can also be set via --local-path). If omitted, a temp folder is used.")]
    public string? LocalPathPositional { get; set; }

    [Option("local-path", Required = false, HelpText = "Local folder path for virtualization root (will be created if needed). If not specified, creates a temp folder and opens it in Explorer")]
    public string? LocalPath { get; set; }

    [Option("pat", Required = false, HelpText = "Personal Access Token for authentication")]
    public string? Pat { get; set; }

    [Option("branch", Required = false, Default = "", HelpText = "Branch to map (defaults to repository's default branch). Overrides branch extracted from URL")]
    public string Branch { get; set; } = "";

    [Option("remote-path", Required = false, Default = "", HelpText = "Subfolder path within the repo to use as root (e.g. src/app). Overrides path extracted from URL")]
    public string RemotePathOption { get; set; } = "";

    // Parsed/derived properties
    public GitProvider Provider { get; private set; }
    public string VirtualizationRoot { get; internal set; } = "";
    public bool AutoGeneratedLocalPath { get; private set; }

    // Azure DevOps specific
    public Uri OrganizationUrl { get; private set; } = null!;
    public string Project { get; private set; } = "";

    // GitHub specific
    public string Owner { get; private set; } = "";

    // Common
    public string Repository { get; private set; } = "";
    public string? PersonalAccessToken { get; private set; }
    public string DefaultBranch => Branch;
    public string RemotePath { get; private set; } = "";  // Normalized: no leading/trailing slashes, forward slashes

    // Generic provider - stores the URL as-is for cloning
    public string CloneUrl { get; private set; } = "";

    // Regex to parse ADO Git URLs:
    //   https://<org>.visualstudio.com/<project>/_git/<repo>[?path=/folder]
    //   https://<org>.visualstudio.com/_git/<repo>[?path=/folder]  (project = repo)
    //   https://dev.azure.com/<org>/<project>/_git/<repo>[?path=/folder]
    //   https://dev.azure.com/<org>/_git/<repo>[?path=/folder]  (project = repo)
    private static readonly Regex AdoUrlRegex = new(
        @"^https://(?:(?<org>[^./]+)\.visualstudio\.com|dev\.azure\.com/(?<org>[^/]+))(?:/(?<project>[^/]+))?/_git/(?<repo>[^/?]+)/?(?:\?.*)?$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    // Regex to parse GitHub URLs:
    //   https://github.com/<owner>/<repo>
    //   https://github.com/<owner>/<repo>/tree/<branch>
    //   https://github.com/<owner>/<repo>/tree/<branch>/<path>
    //   https://github.com/<owner>/<repo>/blob/<branch>/<path>
    private static readonly Regex GitHubUrlRegex = new(
        @"^https://github\.com/(?<owner>[^/]+)/(?<repo>[^/?#]+)(?:/(?:tree|blob)/(?<branch>[^/]+)(?<path>/.*)?)?",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static readonly Regex CommitShaRegex = new(
        @"^[0-9a-f]{40}$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>Validates and processes the parsed options. Call after parsing.</summary>
    public void Validate()
    {
        var url = Url.Trim();

        // Try Azure DevOps first
        var adoMatch = AdoUrlRegex.Match(url);
        if (adoMatch.Success)
        {
            ValidateAzureDevOps(adoMatch, url);
        }
        else
        {
            // Try GitHub
            var gitHubMatch = GitHubUrlRegex.Match(url);
            if (gitHubMatch.Success)
                ValidateGitHub(gitHubMatch, url);
            else
                ValidateGeneric(url);
        }

        // --remote-path overrides any path extracted from the URL
        if (!string.IsNullOrEmpty(RemotePathOption))
            RemotePath = RemotePathOption.Replace('\\', '/').Trim('/').Trim();
    }

    private void ValidateAzureDevOps(Match match, string url)
    {
        Provider = GitProvider.AzureDevOps;

        var org = match.Groups["org"].Value;
        Repository = match.Groups["repo"].Value;
        // If project is not specified in URL, it defaults to the repository name
        Project = match.Groups["project"].Success && !string.IsNullOrEmpty(match.Groups["project"].Value)
            ? match.Groups["project"].Value
            : Repository;

        // Determine org URL format
        if (url.Contains(".visualstudio.com", StringComparison.OrdinalIgnoreCase))
            OrganizationUrl = new Uri($"https://{org}.visualstudio.com");
        else
            OrganizationUrl = new Uri($"https://dev.azure.com/{org}");

        SetupLocalPath();
        SetupAuthentication();

        // Extract optional path and version from URL query string
        // ?path=/folder/subfolder&version=GB<branchname>
        RemotePath = "";
        if (Uri.TryCreate(url, UriKind.Absolute, out var uri) && !string.IsNullOrEmpty(uri.Query))
        {
            var query = System.Web.HttpUtility.ParseQueryString(uri.Query);

            // Extract path parameter
            var pathParam = query["path"];
            if (!string.IsNullOrEmpty(pathParam))
            {
                RemotePath = pathParam.Replace('\\', '/').Trim('/').Trim();
            }

            // Extract version parameter (only GB = Git Branch is supported)
            var versionParam = query["version"];
            if (!string.IsNullOrEmpty(versionParam))
            {
                if (versionParam.StartsWith("GC", StringComparison.OrdinalIgnoreCase))
                    throw new ArgumentException(
                        "Commit-based URLs (version=GC...) are not supported. Use a branch instead (version=GB<branch>).");

                if (versionParam.StartsWith("GT", StringComparison.OrdinalIgnoreCase))
                    throw new ArgumentException(
                        "Tag-based URLs (version=GT...) are not supported. Use a branch instead (version=GB<branch>).");

                if (!versionParam.StartsWith("GB", StringComparison.OrdinalIgnoreCase))
                    throw new ArgumentException(
                        $"Unrecognised version parameter: '{versionParam}'. Only branch URLs are supported (version=GB<branch>).");

                if (string.IsNullOrEmpty(Branch))
                    Branch = versionParam[2..];
            }
        }
    }

    private void ValidateGitHub(Match match, string url)
    {
        Provider = GitProvider.GitHub;

        Owner = match.Groups["owner"].Value;
        Repository = match.Groups["repo"].Value;

        // Remove .git suffix if present
        if (Repository.EndsWith(".git", StringComparison.OrdinalIgnoreCase))
            Repository = Repository[..^4];

        SetupLocalPath();
        SetupAuthentication();

        // Extract branch and path from URL if present
        // https://github.com/owner/repo/tree/branch/path/to/folder
        if (match.Groups["branch"].Success && !string.IsNullOrEmpty(match.Groups["branch"].Value))
        {
            var branchValue = match.Groups["branch"].Value;

            if (CommitShaRegex.IsMatch(branchValue))
                throw new ArgumentException(
                    "Commit-based URLs are not supported. Use a branch instead " +
                    "(e.g. https://github.com/owner/repo/tree/<branch>).");

            if (string.IsNullOrEmpty(Branch))
                Branch = branchValue;
        }

        if (match.Groups["path"].Success && !string.IsNullOrEmpty(match.Groups["path"].Value))
        {
            RemotePath = match.Groups["path"].Value.Replace('\\', '/').Trim('/').Trim();
        }
    }

    private void ValidateGeneric(string url)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)
            || (uri.Scheme != "https" && uri.Scheme != "http" && uri.Scheme != "git"))
        {
            throw new ArgumentException(
                $"Invalid URL: '{url}'. Expected an HTTPS or Git URL " +
                "(e.g. https://gitlab.com/owner/repo.git).");
        }

        Provider = GitProvider.Generic;
        CloneUrl = url;

        // Try to extract a repo name from the URL path for temp folder naming
        var lastSegment = uri.AbsolutePath.TrimEnd('/').Split('/').LastOrDefault() ?? "repo";
        if (lastSegment.EndsWith(".git", StringComparison.OrdinalIgnoreCase))
            lastSegment = lastSegment[..^4];
        Repository = string.IsNullOrEmpty(lastSegment) ? "repo" : lastSegment;

        SetupLocalPath();
        SetupAuthentication();
    }

    private void SetupLocalPath()
    {
        var path = !string.IsNullOrWhiteSpace(LocalPath) ? LocalPath : LocalPathPositional;
        if (string.IsNullOrWhiteSpace(path))
        {
            var tempFolder = Path.Combine(Path.GetTempPath(), $"WinGitFS_{Repository}_{Guid.NewGuid():N}");
            VirtualizationRoot = tempFolder;
            AutoGeneratedLocalPath = true;
        }
        else
        {
            VirtualizationRoot = Path.GetFullPath(path.Trim());
            AutoGeneratedLocalPath = false;
        }
    }

    private void SetupAuthentication()
    {
        if (!string.IsNullOrWhiteSpace(Pat))
            PersonalAccessToken = Pat;
    }
}
