using System.Diagnostics;
using System.Runtime.InteropServices;
using CommandLine;
using WinGitFS;
using Microsoft.Extensions.Logging;

using var loggerFactory = LoggerFactory.Create(builder =>
{
    builder
        .AddSimpleConsole(o =>
        {
            o.SingleLine = true;
            o.TimestampFormat = "HH:mm:ss ";
        })
        .SetMinimumLevel(LogLevel.Debug);
});

var logger = loggerFactory.CreateLogger("WinGitFS");

return await Parser.Default.ParseArguments<GitFsOptions>(args)
    .MapResult(
        async options => await RunAsync(options),
        errors => Task.FromResult(1));

async Task<int> RunAsync(GitFsOptions options)
{
    IGitClient? gitClient = null;
    var createdVirtualizationRoot = false;

    try
    {
        // Validate and process parsed options
        options.Validate();

        if (!Environment.Is64BitProcess)
        {
            logger.LogError("WinGitFS must run as a 64-bit process.");
            return 2;
        }

        if (!options.AutoGeneratedLocalPath && Directory.Exists(options.VirtualizationRoot))
        {
            // Existing folder: append a leaf name derived from remote path or repo name
            var leaf = !string.IsNullOrEmpty(options.RemotePath)
                ? options.RemotePath.Split('/').Last()
                : options.Repository;
            var subPath = Path.Combine(options.VirtualizationRoot, leaf);

            if (Directory.Exists(subPath))
            {
                logger.LogError("The path '{SubPath}' already exists. Remove it or specify a different path.", subPath);
                return 2;
            }

            options.VirtualizationRoot = subPath;
            logger.LogInformation("Using subfolder: {SubPath}", subPath);
        }

        Directory.CreateDirectory(options.VirtualizationRoot);
        createdVirtualizationRoot = true;
        logger.LogInformation("Created virtualization root: {Root}", options.VirtualizationRoot);

        // Create appropriate Git client based on provider
        gitClient = await CreateGitClientAsync(options);

        // Validate credentials and repository access early
        logger.LogInformation("Validating access...");
        await gitClient.ValidateAsync();

        // Fetch default branch if not specified
        if (string.IsNullOrEmpty(options.Branch))
        {
            options.Branch = await gitClient.GetDefaultBranchAsync();
        }
        logger.LogInformation("Using branch: {Branch}", options.Branch);

        using var provider = new GitFsProvider(
            options,
            gitClient,
            loggerFactory.CreateLogger<GitFsProvider>());

        // Pin the provider to prevent GC collection - ProjFS native callbacks require
        // the managed delegate pointers to stay valid for the lifetime of the virtualization.
        var providerHandle = GCHandle.Alloc(provider);

        // Handle Ctrl+C gracefully
        using var cts = new CancellationTokenSource();
        ConsoleCancelEventHandler ctrlCHandler = (_, e) =>
        {
            e.Cancel = true; // Prevent immediate termination
            cts.Cancel();
        };
        Console.CancelKeyPress += ctrlCHandler;

        try
        {
            provider.Start(new Meziantou.Framework.Win32.ProjectedFileSystem.ProjectedFileSystemStartOptions
            {
                UseNegativePathCache = true,
            });

            logger.LogInformation("WinGitFS running at {Root}", options.VirtualizationRoot);
            LogRepositoryInfo(options);
            logger.LogInformation("Press Enter or Ctrl+C to stop.");

            // Open Explorer if path was auto-generated
            if (options.AutoGeneratedLocalPath)
            {
                Process.Start("explorer.exe", options.VirtualizationRoot);
            }

            // Wait for Enter key or Ctrl+C
            try
            {
                while (!cts.Token.IsCancellationRequested && Console.KeyAvailable == false)
                {
                    await Task.Delay(100, cts.Token);
                }
                if (Console.KeyAvailable)
                    Console.ReadKey(intercept: true);
            }
            catch (OperationCanceledException) { }

            provider.Stop();
        }
        finally
        {
            providerHandle.Free();
            Console.CancelKeyPress -= ctrlCHandler;
        }

        return 0;
    }
    catch (ArgumentException ex)
    {
        logger.LogError(ex, "Invalid arguments.");
        return 2;
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Fatal error.");
        return 1;
    }
    finally
    {
        gitClient?.Dispose();

        if (createdVirtualizationRoot && Directory.Exists(options.VirtualizationRoot))
        {
            logger.LogInformation("Cleaning up virtualization root: {Root}", options.VirtualizationRoot);
            while (Directory.Exists(options.VirtualizationRoot))
            {
                try
                {
                    Directory.Delete(options.VirtualizationRoot, recursive: true);
                    logger.LogInformation("Virtualization root deleted.");
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to delete virtualization root.");
                    Console.Write("Retry deletion? [Y/n] ");
                    var key = Console.ReadKey(intercept: false);
                    Console.WriteLine();
                    if (key.KeyChar is 'n' or 'N')
                    {
                        logger.LogWarning("Skipped. You may need to delete it manually: {Root}", options.VirtualizationRoot);
                        break;
                    }
                }
            }
        }
    }
}

async Task<IGitClient> CreateGitClientAsync(GitFsOptions options)
{
    var cloneUrl = BuildCloneUrl(options);
    return await GitProcessClient.CloneAsync(
        cloneUrl,
        loggerFactory.CreateLogger<GitProcessClient>(),
        options.RemotePath,
        options.Branch);
}

string BuildCloneUrl(GitFsOptions options)
{
    string baseUrl = options.Provider switch
    {
        GitProvider.AzureDevOps => $"{options.OrganizationUrl.ToString().TrimEnd('/')}/{options.Project}/_git/{options.Repository}",
        GitProvider.GitHub => $"https://github.com/{options.Owner}/{options.Repository}.git",
        GitProvider.Generic => options.CloneUrl,
        _ => throw new InvalidOperationException($"Unknown provider: {options.Provider}"),
    };

    if (string.IsNullOrEmpty(options.PersonalAccessToken))
        return baseUrl;

    // Embed PAT in the clone URL so on-demand blob fetches also authenticate
    var builder = new UriBuilder(baseUrl);
    builder.UserName = options.Provider == GitProvider.GitHub ? "x-access-token" : "pat";
    builder.Password = options.PersonalAccessToken;
    return builder.Uri.AbsoluteUri;
}

void LogRepositoryInfo(GitFsOptions options)
{
    switch (options.Provider)
    {
        case GitProvider.AzureDevOps:
            logger.LogInformation("Repository: {Org}/{Project}/_git/{Repo}", options.OrganizationUrl, options.Project, options.Repository);
            break;
        case GitProvider.GitHub:
            logger.LogInformation("Repository: github.com/{Owner}/{Repo}", options.Owner, options.Repository);
            break;
        case GitProvider.Generic:
            logger.LogInformation("Repository: {Url}", options.CloneUrl);
            break;
    }

    if (!string.IsNullOrEmpty(options.RemotePath))
    {
        logger.LogInformation("Remote path: /{Path}", options.RemotePath);
    }
}
